//Container of the Raymarch (Add jump/Add Trail/Add Secondary spheres) 
struct RaymarchStruct
{
    //Actor Variables
    float3 ActorPosition;
    float3 ActorRotationForward;
    float3 ActorRotationRight;
    float3 ActorRotationUp;
    float3x3 ActorRotationMatrix;
    
    //Sdf Variables
    float3 SphereCenters[10];
    float3 ExternalSpheresCenters[10];
    float ExternalSpheresRadii[10];
    int ExternalSpheresCount;
    float ExternalRotationSpeed;
    float SphereRadii[10];
    int SphereCount;
    float IsBox;
    
    //Texture Variables
    float UseTexture;
    Texture2D Tex;
    SamplerState TexSampler;
    float3 BaseColor;
    float IsSnow;
    Texture2D TexSnow;
    SamplerState TexSnowSampler;
    float snowIndex;
    
    
    //Noise Variables
    float IsNoise;
    float noiseIndex;
    float noiseScale;
    float iTime;
    
    
    //====================================================
    // Signed Distance Functions (SDF)
    //====================================================
    float sdBox(float3 center, float3 halfSize, float roundness)
    {
        float3 q = abs(center) - halfSize;
        return length(max(q, 0.0)) - roundness;
    }

    float sdSphere(float3 p, float3 center, float r)
    {
        return length(p - center) - r;
    }

    float smin(float a, float b, float k)
    {
        float h = clamp(0.5 + 0.5 * (b - a) / k, 0.0, 1.0);
        return lerp(b, a, h) - k * h * (1.0 - h);
    }
    
    //====================================================
    // Map will create SDFs and return the pixels modified 
    //====================================================
    float map(float3 p,float3 BoxCenter,float3 BoxSize,float BoxRoundness,float Smoothness)
    {
        //Add every sdf that need to have noise on it right here
        
        float d=999999.0f;
        for (int i = 0; i < SphereCount; i++) {
            float di = sdSphere(p, SphereCenters[i], SphereRadii[i]);
            d = smin(d, di, Smoothness);
        }
        
        if (IsBox>0)
        {
            float d1= sdBox(p-BoxCenter, BoxSize*0.5, BoxRoundness);
            d=smin(d, d1, Smoothness);
        }
        
        if (IsNoise>0)
        {
            float noise = sin(noiseScale * p.x + iTime) * sin(noiseScale * p.z + iTime) * sin(noiseScale * p.y + iTime) * noiseIndex;
            d += noise;
        }
        
        //Add every sdf that doesn't need noise on it right here
        
        for (int i = 0; i < ExternalSpheresCount; i++) {
            float Xsymbol= sign(ExternalSpheresCenters[i].x);
            float Zsymbol= sign(ExternalSpheresCenters[i].z);
            float3 currentCenter = float3(cos(iTime*(ExternalRotationSpeed*Xsymbol))*ExternalSpheresCenters[i].x,sin(iTime*(ExternalRotationSpeed*Zsymbol))*ExternalSpheresCenters[i].z,ExternalSpheresCenters[i].y);
            float di = sdSphere(p, currentCenter, ExternalSpheresRadii[i]);
            d = smin(d, di, Smoothness);
        }

       
        return d;
    }
    
    //====================================================
    // getNormal will obtain and return the normal of the SDFs
    //====================================================

    float3 getNormal(float3 p, float3 BoxCenter, float3 BoxSize, float BoxRoundness, float Smoothness)
    {
        float eps = 0.0001;
        float3 dx = float3(eps, 0.0, 0.0);
        float3 dy = float3(0.0, eps, 0.0);
        float3 dz = float3(0.0, 0.0, eps);

        float nx = map(p + dx, BoxCenter, BoxSize, BoxRoundness, Smoothness) - map(p - dx, BoxCenter, BoxSize, BoxRoundness, Smoothness);
        float ny = map(p + dy, BoxCenter, BoxSize, BoxRoundness, Smoothness) - map(p - dy, BoxCenter, BoxSize, BoxRoundness, Smoothness);
        float nz = map(p + dz, BoxCenter, BoxSize, BoxRoundness, Smoothness) - map(p - dz, BoxCenter, BoxSize, BoxRoundness, Smoothness);

        return normalize(float3(nx, ny, nz));
    }

    //====================================================
    // Triplanar Texture will apply the given texture to the object no matter the shape of it
    //====================================================

    float3 SampleTriplanar(Texture2D Tex, SamplerState Sampler, float3 p, float3 normal, float scale)
    {
        
        float3 blend = abs(normal);
        blend = pow(blend, 4.0);
        blend /= (blend.x + blend.y + blend.z);

        float2 uvX = p.yz * scale;
        float2 uvY = p.zx * scale;
        float2 uvZ = p.xy * scale;

        uvX = frac(uvX);
        uvY = frac(uvY);
        uvZ = frac(uvZ);

        float3 colX = Tex.Sample(Sampler, uvX).rgb;
        float3 colY = Tex.Sample(Sampler, uvY).rgb;
        float3 colZ = Tex.Sample(Sampler, uvZ).rgb;

        return colX * blend.x + colY * blend.y + colZ * blend.z;
    }

    //====================================================
    // Triplanar Texture will apply the given texture to the object no matter the shape of it
    //====================================================

    float3 ApplySnow(Texture2D SnowTex, SamplerState SnowSampler, float3 localPos, float3 normal, float scale, float3 baseColor)
    {
        
        float upMask = saturate(normal.z);
        float snowFactor = pow(upMask, snowIndex);
        
        float2 uvX = localPos.yz * scale;
        float2 uvY = localPos.zx * scale;
        float2 uvZ = localPos.xy * scale;

        uvX = frac(uvX);
        uvY = frac(uvY);
        uvZ = frac(uvZ);

        float3 colX = SnowTex.Sample(SnowSampler, uvX).rgb;
        float3 colY = SnowTex.Sample(SnowSampler, uvY).rgb;
        float3 colZ = SnowTex.Sample(SnowSampler, uvZ).rgb;

        float3 blend = abs(normal);
        blend = pow(blend, 4.0);
        blend /= (blend.x + blend.y + blend.z);

        float3 snowTexColor = colX * blend.x + colY * blend.y + colZ * blend.z;
        
        return lerp(baseColor, snowTexColor, snowFactor);
    }

    //====================================================
    // Compile Main Function 
    //====================================================

    float4 RaymarchExecute(float3 CameraPos,float3 WorldPos,float3 ObjectWorldPos,float3 BoxCenter,float3 BoxSize,float BoxRoundness,float Smoothness,int MaxSteps,float MaxDistance,float HitThreshold,float TexScale)
    {
        //Setting up Actor variables
        ActorRotationForward=normalize(ActorRotationForward);
        ActorRotationRight=normalize(ActorRotationRight);
        ActorRotationUp=normalize(ActorRotationUp);
        ActorRotationMatrix = float3x3(ActorRotationForward,ActorRotationRight,ActorRotationUp);

        //Setting up Raymarch Variables
        float3 ro = CameraPos;
        float3 rd = normalize(WorldPos - CameraPos);
        float t = 0.0;
        float3 p;
        bool hit = false;
        float3 localPos;

        //Raymarch loop starts here
        [loop]
        for (int i = 0; i < MaxSteps; i++) 
        {
            p = ro + rd * t;
            localPos = p-ObjectWorldPos;
            localPos=mul(ActorRotationMatrix,localPos);
            float dist = map(localPos,BoxCenter,BoxSize,BoxRoundness,Smoothness);

            if (dist < HitThreshold) {
                hit = true;
                break;
            }
            if (t > MaxDistance) break;

            t += dist;
        }
        //If the ray hits than return the color/texture on the pixel
        if (hit)
        {
            //Only if you want to use a texture, use color otherwise
            if (UseTexture>0.f)
            {
                float3 normal = getNormal(localPos, BoxCenter, BoxSize, BoxRoundness, Smoothness);
                float3 texColor = SampleTriplanar(Tex,TexSampler, localPos, normal, TexScale);
                if (IsSnow>0)
                {
                    texColor = ApplySnow(TexSnow, TexSnowSampler, localPos, normal, TexScale, texColor);
                }
                return float4(texColor, 1.0);
            }
            else
            {
                return float4(BaseColor, 1.0);
            }
        }
        //If the ray doesn't hit return an invisible pixel
        return float4(0, 0, 0, 0);
    }
};



